### ISSUE TITLE
Add SOCKS5 proxy support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nilsbraden/ttrss-reader-fork#229]
```
I've setup TTRSS on a computer with no public IP, and the only way to connect 
to it is by Tor.
I'd love to use ttrss-reader with that server, but the only way to do it is to 
use SOCKS5 proxy provided by orbot.
Can proxy support be added to ttrss-reader?
```

Original issue reported on code.google.com by `TomaszKo...@gmail.com` on 26 Jan 2014 at 9:04

**Comment by nilsbraden** [comment]
Can you provice me with an environment to test this if I implement it or are you available for testing? I can't set this up myself with reasonable effort.

**Comment by languitar** [comment]
There are plenty of free proxies available, e.g. listed here: https://www.socks-proxy.net/. Also, you can install orbot as an Android app and it will create a proxy on your device.

**Comment by jr4** [comment]
added support:  https://github.com/nilsbraden/ttrss-reader-fork/pull/363
