### ISSUE TITLE
Mark as read on scroll

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nilsbraden/ttrss-reader-fork#247]
```
One of my most used features on other readers has always been to be able to 
scroll in the list of articles and have the articles you skip be marked as 
read.  I believe it is in the official tt-rss app as well as a few others like 
greader etc.

Thanks for the consideration.  I'm thrilled to have found this app.
```

Original issue reported on code.google.com by `goo...@part4.net` on 13 Jul 2014 at 3:31

**Comment by mmarsalko** [comment]
I'm wondering if you'd be interested in porting this feature into the latest tt-rss reader? I'm on an ancient build still (1.301 Dec 2021) because I find this feature to be so incredibly useful.
