### ISSUE TITLE
disable media loading

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nilsbraden/ttrss-reader-fork#268]
```
There is a feature to disable image loading in the android client but not yet 
to disable other external media (audio and video).
Today the audio seems to load by itself without clicking on the play bouton.
It would be usefull if we can disable it to not use a lot of data.


```

Original issue reported on code.google.com by `va...@hotmail.fr` on 5 Feb 2015 at 9:32

**Comment by nilsbraden** [comment]
I changed the mentioned preference from "Disable image loading" to "DIsable media loading" and tried to stop the webview from displaying embedded audio and video too. Can you please try this build and report back if it works: https://drive.google.com/open?id=0B2I5LDZK1kOETEtJZ1YzeERQaHM
