### ISSUE TITLE
Option to disable "All Read", "Feed Read", "Feeds Read" buttons

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nilsbraden/ttrss-reader-fork#270]
```
I have never needed the menu options to mark everything as read and actually I 
have pressed it twice by accident with catastrophic results.
So, I request an option to disable those (IMHO) annoyingly dangerous buttons, 
the default behavior would be as before.

I attach a patch with a possible solution, hoping this is enough to be in a 
next release.
```

Original issue reported on code.google.com by `juan...@gmail.com` on 9 Mar 2015 at 11:10

Attachments:
* [patch_hide_mark_as_read.diff](https://storage.googleapis.com/google-code-attachments/ttrss-reader-fork/issue-270/comment-0/patch_hide_mark_as_read.diff)

**Comment by nilsbraden** [comment]
Thank you for providing a patch, I did include it almost unchanged.

I also added the existing Dialog to a situation I forgot before. There is a Dialog which asks on the following occasions now:
* Marking a category as read
* Marking a virtual category as read
* Marking all feeds within a category as read
* Marking all articles as read when using "Show all articles for this category"

I attached a build with the current changes so you can try this. The next update will probably take some more days. You can download the build here: https://drive.google.com/open?id=0B2I5LDZK1kOEWHQtWE1zTWZUeDQ

**Comment by deMattin** [comment]
I liked the feature very much to mark read without app asking me, if i really want.
The workflow now is much worse as before. 
You should have the option to deactivate this dialog! 
Please make this possible. 

And with last update also the mark category button goes away, if you tap on an article in tablet view and is replaced by fav icon.
Mark as fav is not as often neccessary as Mark all read

I see this Patch as a step back in workflow. 
Please make this setable to get old workflow back for User, that know, where they tap on and do not need this annoying dialog, if I really want to do, what I tapped on.
