### ISSUE TITLE
Allow to view all articles from sub categories

### ISSUE THREAD

**Issue by schlamar** [nilsbraden/ttrss-reader-fork#273]
I know there is an option where I can turn this on but I don't want to have this a global setting. I want to have both options available: descend into a specific sub category AND read all articles of a category.

There are two ways to achieve this: 

- use expanders for categories like in the web application
- show an "all article" special sub category

The latter should for example create an article tree like this:

    + Tech
      + All Articles
      + Slashdot
      + LWN 

Where "All Articles" contains all articles from Slashdot and LWN feed.

An expander style is preferable but this is probably much more work so the other solution would suffice as intermediate solution.

**Comment by nilsbraden** [comment]
Have you tried long-pressing on a category -> Show all articles?

**Comment by schlamar** [comment]
Yes, I have seen this in the meantime but it's really inconvenient, not a really good UX actually.

**Comment by schlamar** [comment]
But not much worse than my second proposal so you can skip this one and do proper expanders 	directly :)
