### ISSUE TITLE
"Mark all read" suddenly marks everything read and not only the shown category

### ISSUE THREAD

**Issue by languitar** [nilsbraden/ttrss-reader-fork#274]
With the recent update to version 1.82, the button to mark all read suddenly marks everything read and not only the articles in the currently viewed category. This is a very dangerous change in behavior and I suddenly lost track of a lot of unread articles due to this. Please reenable the old behavior to just mark the viewed feed or virtual feed read with the button.

**Comment by dzieko** [comment]
I have the same problem. Pls revert to the old behavior or at least make it configurable.

**Comment by nilsbraden** [comment]
Thanks for reporting, this should be fixed with the next update. You can retrieve it manually here or wait for the market to update: https://drive.google.com/file/d/0B2I5LDZK1kOEb0ZtM0VZYUZneGs/view?usp=sharing

**Comment by languitar** [comment]
Thanks, works well now.
