### ISSUE TITLE
New articles: Swipe article away to hide

### ISSUE THREAD

**Issue by brdvlps** [nilsbraden/ttrss-reader-fork#275]
It would be a nice and handy feature to swipe uninteresting headlines away in "Fresh articles", like Android notifications. This should also mark them as already read.

**Comment by nilsbraden** [comment]
How would you go about deciding if the user wanted to swipe between feeds or swipe away an article? It's the same movement.

**Comment by brdvlps** [comment]
Sorry, I meant the headlines overview, which appears right after tapping on "Fresh articles". Not the concrete article view.

**Comment by nilsbraden** [comment]
Thats the same view as when you just directly open a feed, there you can swipe left and right for previous and next feed too.

**Comment by brdvlps** [comment]
Ah, I see. Haven't noticed that.
Well, the only option for this feature which comes to my mind is to change the swipe behavior just for the fresh articles view. Don't know if it's worth the effort though.

**Comment by nilsbraden** [comment]
I don't think I'll pursue this any more. If anyone wants to try you're welcome to fork and send a pull request.
