### ISSUE TITLE
Mark as unread doesn't work reliable

### ISSUE THREAD

**Issue by schlamar** [nilsbraden/ttrss-reader-fork#278]
If I mark an article from the article view as unread and go back to the article list, it is suddenly marked again as read...

However, this is not 100% reproducible. I noticed this mainly on mobile network. I have often a pretty bad connection with the mobile network so this could be due to a bad connection.

Whenever this happen, I see all unread items in my article list when going back although I have set the articles list to unread only.

**Comment by schlamar** [comment]
I made a screencast, this should be helpful: https://docs.google.com/file/d/0Bxcf7mYNJYc5QjJROUVYZEp3bmc/edit?usp=docslist_api

**Comment by dominix** [comment]
what happen for me on my tablet is : I open a post, then I swip on the post to read the next post. if I mark the post unread (the second one) it mark the first unread. If I swip many time, sometimes it is only the first that is marked unread, sometimes the number vary, it could be the second or the third post that is marked, while I am on the seven'th.

**Comment by schlamar** [comment]
Haven't seen this for a while, I guess this is fixed.
