### ISSUE TITLE
Allow TTRSS to register as a feed reader in Firefox for Android

### ISSUE THREAD

**Issue by 3ruce** [nilsbraden/ttrss-reader-fork#282]
Firstly, great app, TTRSS is my favourite app on the platform!

As per the attached, Firefox on Android allows you to 'Subscribe to a Page' which then allows you to choose the auto-discovered feed and then select an rss reader of choice. At the moment however, only 'My Yahoo' appears. Is there any way to add TTRSS to this list, in a similar way the php app can be registered with Firefox on the desktop?

![screenshot_2015-04-16-07-35-50](https://cloud.githubusercontent.com/assets/1258786/7174660/8fb9fb12-e40b-11e4-8b26-923847c40178.png)

(I appreciate this is a browser specific request, but it's all in the name of supporting open source!)

**Comment by nilsbraden** [comment]
If I could find anything about this feature I could analyse it and say something about it but whatever combination of search terms I use I cannot find anything. The firefox sourcecode is cluttered with mentions of rss stuff so to grep through it I need a more specific search term. Really strange.

**Comment by 3ruce** [comment]
Hi Nils, this is what I've found which might help in the hunt...

This bug report
https://bugzilla.mozilla.org/show_bug.cgi?id=983435

Leads to this 'activity' page
https://bugzilla.mozilla.org/show_activity.cgi?id=983435

And this patch/code
https://bug983435.bugzilla.mozilla.org/attachment.cgi?id=8400223

Scanning the diff entries at the top, the following may help locate the source
diff --git a/mobile/android/chrome/content/FeedHandler.js b/mobile/android/chrome/content/FeedHandler.js
--- a/mobile/android/chrome/content/FeedHandler.js
+++ b/mobile/android/chrome/content/FeedHandler.js

When googling "/mobile/android/chrome/content/FeedHandler.js" this github page isn't hard to find but I don't know if this is the actual location of Firefox for Android...

https://github.com/mozilla/gecko-dev/blob/master/mobile/android/chrome/content/FeedHandler.js

Does this help at all?

**Comment by 3ruce** [comment]
p.s. there's an addon that might also help with pointers around this...

https://addons.mozilla.org/en-US/android/addon/home-feeds/

**Comment by mdewilde** [comment]
http://starkravingfinkle.org/blog/2013/04/firefox-for-android-subscribing-to-feeds/

Seems this may not be possible, though the article is from 3 years ago.
