### ISSUE TITLE
Dialog popups barely visible in dark theme

### ISSUE THREAD

**Issue by dzieko** [nilsbraden/ttrss-reader-fork#285]
Hello,

1st of all - big thanks for great work.

One small issue: after update to 1.8.4 popup dialogs are barely visible in dark theme.
Pls see attached screenshot.
Non transparent background would be helpful.

thanks in advance, Pawel

![screenshot_2015-04-21-17-50-27](https://cloud.githubusercontent.com/assets/11696581/7285184/2026013c-e943-11e4-94db-f7693512a9c7.png)

**Comment by nilsbraden** [comment]
All current UI improvement issues merged into #284
