### ISSUE TITLE
SSL broken as of 1.85

### ISSUE THREAD

**Issue by idl0r** [nilsbraden/ttrss-reader-fork#287]
Hi,

I just got the 1.85 release and since then I am unable to connect via SSL (self signed tested only). I'll try to post the exact error here ASAP.

**Comment by idl0r** [comment]
I am unable to copy the message but most important: Trust anchor for certification path not found.
It worked fine in 1.84.

**Comment by dzieko** [comment]
I confirm. Pls see attached screenshot.

![img_20150506_151406](https://cloud.githubusercontent.com/assets/11696581/7493629/e3eafc3e-f402-11e4-908b-9dfa164e6629.JPG)

**Comment by thomasgg23** [comment]
Same problem for me since update to 1.85 with self-signed certificates.

**Comment by nilsbraden** [comment]
Can anyone please send me a mail with the URL of your ttrss server? I don't need any credentials.
-> ttrss@nilsbraden.de

**Comment by idl0r** [comment]
Done.

**Comment by nilsbraden** [comment]
Think I got it, see this release: [Release v1.85.1](../releases/tag/v1.85.1)
Can you please confirm that it works? You have to disable the newly added preference "SSL->Use Google Play services: Provider-Installer".

**Comment by nilsbraden** [comment]
idl0r has confirmed it working for him, I'll update the play store and close this issue. Please comment again if it doesn't work for you though.

**Comment by rgletters** [comment]
I disabled the SSL pref. in v. 1.85.1 but new articles are still not loaded.

**Comment by idl0r** [comment]
You may have to restart the APP. Does that work for you?

**Comment by dzieko** [comment]
idl0r,
I still have the same problem -- Trust anchor for certification path not found.
I have reinstalled the whole app to be 200% sure that some old configuration
is not being used.

**Comment by nilsbraden** [comment]
Please mail me the url of your installation.

**Comment by dzieko** [comment]
I just did.

**Comment by rgletters** [comment]
Versions 1.85.1 and 1.85.0 don't load anything. Back to 1.84.1 for the moment and working.

**Comment by nilsbraden** [comment]
For those who still have this problem please try again with the current play store version after rebooting the device with the following settings:
 * Use Google Play services...: disabled
 * Accept all SSL certificates: enabled
 * Trust all hosts: enabled
 * Digest: disabled

Or if you have a custom keystore:
 * Use Google Play services...: disabled
 * Accept all SSL certificates: disabled
 * Trust all hosts: disabled
 * Custom Keystore: enabled
 * Digest: disabled

**Comment by rgletters** [comment]
nilsbraden,

I don't have any custom keystore so I have tested the first settings with v.1.85.1 after rebooting and still have the same problem: for 1 second, counters are incremented and then set back to their initial value and nothing new is loaded.

**Comment by idl0r** [comment]
Are your certs still valid? Do you use old/insecure values for your cert that may have been banned? Did you use HSTS by chance?
On my reader I just use a self-signed cert, nothing special except 4096bit and SHA2 and it works fine with the disabled "Use Google Play services" setting.

**Comment by rgletters** [comment]
idl0r,

I guess my settings are correct because v 1.84 is still working fine with all SSL settings disabled. My server is based on openshift without SSL, and I don't use HSTS. 
I don't see any error, just nothing is loaded. Is there a log somewhere?

**Comment by idl0r** [comment]
Well, because it works in 1.84 doesn't mean it's correct. So according to your answer you don't use SSL at all but the app throws an error regarding SSL anyway?

**Comment by rgletters** [comment]
idl0r,

That's it, I don't use SSL and with the same basic settings (url, user and password) 1.84 works fine and 1.85.1 doesn't.

I have just done a 1.85.1 install from scratch with the same basic settings: categories and feeds are created, counters are incremented for a while and then cleared, and all feeds remain empty. Changing SSL settings doesn't affect. 

The app does not throw any error or I don't know how to see it, symptoms are that 1.85.1 does not load any article while 1.84 do.

**Comment by albatros69** [comment]
Hello,
I'm also having SSL issues since the update to 1.85. Mines are related to SSLv3 (see screenshot attached): it's likely that the TTRSS instance I'm using recently deactivated the now deprecated SSLv3 version of TLS, causing incompatibility with the SSL/TLS library implemented in TTRSSReader.
![screenshot_2015-05-18-08-19-21](https://cloud.githubusercontent.com/assets/5740149/7676688/53fcd3ca-fd46-11e4-9600-6dbf1e2b9c3a.png)
Deactivating the new "Google Play" option doesn't help. Let me know if I can help you troubleshooting the problem.

**Comment by idl0r** [comment]
*I* wouldn't treat that as a bug then. Is it possible for you to fix the SSL cipher?

**Comment by albatros69** [comment]
Unfortunately, I'm not managing the TTRSS instance and even if I were, I would'nt downgrade: SSLv3 is deprecated and vulnerable in many ways (https://access.redhat.com/articles/1232123 for instance). This version is excluded now in the vast majority of distributions. So, not supporting a recent version of TLS (v1.1 at least) will anyway be blocking very soon!

**Comment by Unode** [comment]
Was also having intermittent SSL connections problems. If I open TTRSS immediately after a reboot everything worked. Exited the app and reopened some minutes later and I could no longer connect.
Disabling the "Use Google Play services" option fixed it for me.

**Comment by nilsbraden** [comment]
Is this still an issue?

**Comment by dzieko** [comment]
I'm afraid - yes, at least for me.
P

**Comment by onceking** [comment]
@nilsbraden, shot you a email with a server with valid ssl cert but getting SSL error in 1.85

**Comment by lkwg82** [comment]
for me it is gone.

**Comment by nilsbraden** [comment]
@onceking: Sry for the late reply. I looked into this and I couldn't really figure out what is wrong with the certificate but once I disabled the play services provider-installer (SSL Preferences of the app) it seemed to work. So I guess there is something about the certificate which is considered insecure by Google.

**Comment by dzieko** [comment]
Hi Nils and All,

it looks like "trust anchor" error can be thrown also when web server
does not present full certificate chain. Pls take a look at this:
http://stackoverflow.com/a/16302527

it works for me now. Thanks.

**Comment by nilsbraden** [comment]
Thank you everyone, I'm closing this for now. Please open a new issue if the problem persists.
