### ISSUE TITLE
"Feed read" button disappears when reading a feed's article in tablet layout

### ISSUE THREAD

**Issue by psy-q** [nilsbraden/ttrss-reader-fork#289]
One of the big advantages of tablet layout was that I could decide to mark the whole feed as read while reading one of its stories on the right. Now this is only possible using the tiny "..." ellipsis menu as the "Feed read" button disappears on reading an article and only reappears when I exit back to the category and reopen the feed without opening an article in it.

Can't the "Feed read" button just stay there as it used to do?

**Comment by nilsbraden** [comment]
I tried to change the appearance of the buttons, please test the next release. Thank you.
