### ISSUE TITLE
Server-local cached images failed to load when not pre-caching

### ISSUE THREAD

**Issue by kees** [nilsbraden/ttrss-reader-fork#290]
It looks like my guess at fixing Issue #269 wasn't good enough.

I've finally gotten a full build environment set up, and after a few days of beating my head on a wall, I've got a solution. It seem that WebView isn't as friendly as I'd like, and doesn't provide call-backs for authentication requests.

**Comment by nilsbraden** [comment]
Thank you! I wont merge it right now though since I first have to tackle to connection problems with self-signed certificates. This will lead to a new bugfix release and afterwards I'll include new functionality again.
