### ISSUE TITLE
blank screen when trying to publish articles in firefox

### ISSUE THREAD

**Issue by drewbenn** [nilsbraden/ttrss-reader-fork#293]
In Firefox 38.0.5 on Android 4.1.1, a Samsung 7" Galaxy Tab tablet, TTRSS-Reader 1.85.1 (version-code 1851) installed from Google's Play store. I click the 3-vertical-dots to bring up the settings, and then the Share icon, and then "Publish content," and I get a mostly-empty white screen with a title bar and keyboard, but I can't actually publish. On my phone (Android 4.4.2 ), publishing works correctly with the same versions of TTRSS-Reader and Firefox: the Publish content screen has Title, URL, and a Content field where I can add my own text.

![ttrss_no_publish](https://cloud.githubusercontent.com/assets/2680450/8151151/6d1872ae-12ba-11e5-9378-b954fe6ace7f.jpg)

**Comment by nilsbraden** [comment]
Should be fixed with the next update, thanks for reporting.
