### ISSUE TITLE
HTML-tags in title

### ISSUE THREAD

**Issue by UksusoFF** [nilsbraden/ttrss-reader-fork#297]
Sometimes html tags has broken full article view. For eg:

```
  <item>
    <title>Програмный вывод &amp;lt;title&amp;gt; к определенному типу материалов</title>
    <link>http://dru.io/question/2388</link>
    <description>...</description>
     <pubDate>08.07.2015 - 15:34</pubDate>
 <dc:creator>animan</dc:creator>
 <guid isPermaLink="false">/question/2388</guid>
  </item>
```

Images:
![screenshot_2015-07-08-18-21-07](https://cloud.githubusercontent.com/assets/1931442/8588944/5a2dd90c-2621-11e5-8925-554d10844741.png)
![screenshot_2015-07-08-18-21-14](https://cloud.githubusercontent.com/assets/1931442/8588945/5a315ba4-2621-11e5-8dfe-0a7977f2f6c5.png)

**Comment by nilsbraden** [comment]
I can't think how this can be a problem of the client since I do no parsing of RSS on the client. Does this happen in the default web-UI too? If yes you need to head over to tt-rss.org and open a bug there.

**Comment by UksusoFF** [comment]
No, this error only in android app.

**Comment by nilsbraden** [comment]
I am unable to reproduce this issue even when adding the given example title to an existing article. Can you provide me with a feed-url that shows the described problem?

**Comment by UksusoFF** [comment]
Try this feed: http://demo.iamdrunk.ru/rss/test.php
