### ISSUE TITLE
Item listing cuts off bottom of items with long titles

### ISSUE THREAD

**Issue by rfunk** [nilsbraden/ttrss-reader-fork#299]
It used to be that items in the list had a variable height as appropriate for the amount of text shown. But an update within the last few months changed it so that list items have a fixed height, no matter the content. (I suspect the styles.xml change in commit d4687765, but I don't really know Android layouts.) That means that items with long titles or long feed names now get cut off. I see it most often with item titles in Neil Gaiman's Tumblr feed, as well as the feed title for the Saturday Morning Breakfast Cereal webcomic.
![2015-07-12 17 40 33](https://cloud.githubusercontent.com/assets/21960/8639059/4d76ce4e-289c-11e5-87d8-29b6aa008424.png)

**Comment by nilsbraden** [comment]
I'd suggest you direct this complaint at the authors who are abusing the title field to include the content instead. I'm not going to scroll for hours because some authors do this, if I want to read the content I open the feed. The article view should show the full title, or doesn't it?
