### ISSUE TITLE
Error on connection

### ISSUE THREAD

**Issue by Kraymer** [nilsbraden/ttrss-reader-fork#300]
Same symptoms than #102
v1.85.2

I've setup a server instance on openshift.com, enabled API access.
In the preferences, put the url with correct protocol (https) and login/pass.

Connection fails with msg

    Use JsonReader.SetLenient(true) to accept malformed JSON at line 1 column 1 path $

How can i debug my way out of this situation ?

**Comment by nilsbraden** [comment]
You can start by sending requests to your server manually with curl as described here: https://tt-rss.org/gitlab/fox/tt-rss/wikis/ApiReference
Also you can try to collect more detailed logs with adb (from the Android SDK) or an app like Catlog as described here: https://github.com/nilsbraden/ttrss-reader-fork/wiki/Troubleshooting

**Comment by Kraymer** [comment]
Thanks for the pointers.
