### ISSUE TITLE
Image cache no longer working for some? feeds

### ISSUE THREAD

**Issue by idl0r** [nilsbraden/ttrss-reader-fork#301]
Hi,

I have the feed of "narf-archive.com" subscribed which can be found here:
https://narf-archive.com/clickstream/?&permalink=null&tags=&limit=44&format=rss20
This is an example of an image entry:
```
<item>
  <title>25da91626494fbbd9dba54009cd5778de07a020a</title>
  <pubDate>Mon, 14 Sep 2015 23:26:09 +0000</pubDate>
  <category>imgur</category>
  <link>https://narf-archive.com/dp/25da91626494fbbd9dba54009cd5778de07a020a</link>
  <media:thumbnail url="//t.narf-archive.com/pix/thumbs/25da91626494fbbd9dba54009cd5778de07a020a-80s.jpeg"/>
  <media:content url="//narf-archive.com/pix/25da91626494fbbd9dba54009cd5778de07a020a.jpeg"/>
  <guid isPermaLink="false">https://narf-archive.com/dp/25da91626494fbbd9dba54009cd5778de07a020a</guid>
  <description><![CDATA[
    
    <img src="//narf-archive.com/pix/25da91626494fbbd9dba54009cd5778de07a020a.jpeg"/>
    
    <br/>
    Date: Mon, 14 Sep 2015 23:26:09 +0000<br/>
    From: imgur<br/>
    Tags: <br/>
    ]]>
  </description>
</item>
```

Any ideas what could cause it to no longer work? It might be their fault, because they changed some feed stuff recently. I don't recall how exactly the image cache works so I'm not yet sure whether it's a bug in the cacher or on their side.

**Comment by idl0r** [comment]
https://github.com/nilsbraden/ttrss-reader-fork/commit/ea4f643155fc6b9045be80d30f628144db14a2fc
Thanks!

**Comment by nilsbraden** [comment]
Oh, didn't know this was related but obviously it is. :)
