### ISSUE TITLE
How to visit a URL using a browser

### ISSUE THREAD

**Issue by DamienCassou** [nilsbraden/ttrss-reader-fork#307]
In other feed readers I've used, I've always found a way to go from a post in the feed reader to the post's url in the web browser. I sometimes use that to get the original formatting of an article or to view a video in context. Is there such a thing in ttrss-reader?

**Comment by nilsbraden** [comment]
Actually there is: The headline of the article view (which has a different background) is an anchor an can be clicked. This is the url of the article.
