### ISSUE TITLE
Random auth with auth_imap enabled 

### ISSUE THREAD

**Issue by veretcle** [nilsbraden/ttrss-reader-fork#311]
With the current version of ttrss and current version of the application, I get the following error message:
Couldn't login to your account please check your credentials.

On the imap server auth log sometimes it receives the clear password (and then it works just fine), but most of the time it recieves an hash which the dovecot imap server cannot understand.

Is there a way to tell ttrss-reader not to use hashed password ?

**Comment by nilsbraden** [comment]
The password isn't hashed, it's base64 encoded which allows for encoding and decoding without loss of data. I only use this because the server used to have problems with properly escaping special characters in the password.

I have no idea what auth_imap does.

**Comment by veretcle** [comment]
Auth_imap sends the clear password directly to the configured imap socket.

If there is a way to know if the password is based-64 encoded, I will just modify the code there. Thanks for helping me.
