### ISSUE TITLE
Frequent force close on mark all read

### ISSUE THREAD

**Issue by dzieko** [nilsbraden/ttrss-reader-fork#314]
I run latest version of this great app on Android 6.0.1 on nexus 6.

App crashes very frequently when I do "mark all read". This happens also on sony xperia z4 tablet running Android 6.0.1. This problem was present also on previous versions of Android on both devices.

How can I help to debug this further?
Thanks in advance.

**Comment by gbloice** [comment]
I also suffer from this when marking All Read for an individual feed.  Android 6.0.1 on Nexus 5x, but I used to get it on my Nexus 4 as well.

**Comment by nilsbraden** [comment]
I have seen this error too and also have a lot of reports in the play store. The stacktrace in question:

> java.lang.IllegalStateException: this should only be called when the cursor is valid
>  android.widget.CursorAdapter.getView(CursorAdapter.java:278)
>  android.widget.AbsListView.obtainView(AbsListView.java:2346)
>  android.widget.ListView.makeAndAddView(ListView.java:1876)
>  android.widget.ListView.fillDown(ListView.java:702)
>  android.widget.ListView.fillGap(ListView.java:666)
>  android.widget.AbsListView.trackMotionScroll(AbsListView.java:5053)
>  android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4601)
>  android.os.Handler.handleCallback(Handler.java:739)
>  android.os.Handler.dispatchMessage(Handler.java:95)
>  android.os.Looper.loop(Looper.java:148)
>  android.app.ActivityThread.main(ActivityThread.java:5461)
>  java.lang.reflect.Method.invoke(Native Method) 

If anyone finds the cause for this I am more than happy to fix it but since I have spent some time on this and found nothing I am for now leaving this as it is.
