### ISSUE TITLE
Update feeds in background at given time

### ISSUE THREAD

**Issue by giovi321** [nilsbraden/ttrss-reader-fork#315]
It would be great to add as a feature the possibility to update the feeds automatically in the background (like a service) at a given time set by the user. It is a functionality implemented in the financial times app and I find it very useful. It won't affect the battery because you would set it to update the feeds before waking up in the morning for example, therefore the phone would be connected both to power and to wifi.

**Comment by nilsbraden** [comment]
You might want to try the apps Tasker or Llama since with those you can use the described automation feature. In Tasker you find this as a plugin which allows updating all feeds or starting the ImageCache.
