### ISSUE TITLE
Feeds do not update at app startup

### ISSUE THREAD

**Issue by giovi321** [nilsbraden/ttrss-reader-fork#316]
Despite I ticked the option to fetch articles and images in background, the feeds are not being updated.
See screenshot of the setting: http://imgur.com/UZB6DVx
Could this issue be related to the fact that the app is always running in the background and I am unable to kill it?

**Comment by nilsbraden** [comment]
The preferences you selected are to be read as follows:
1. Update articles+images on startup
2. Do 1. only on wifi
So if you are not on wifi nothing is updated. Not sure if this should be like this but it is.

The app running in the background thing is android (or mobile operating system) specific. Apps are not actually running but kind of suspended and are built in a way to always return to the last saved state when beeing revived.
