### ISSUE TITLE
Pop-up dialogs using low contrast/invisible text

### ISSUE THREAD

**Issue by abcminiuser** [nilsbraden/ttrss-reader-fork#321]
The latest 1.90.0 build shows poorly contrasted pop-ups on my Nexus 6P, running stock Marshmallow.<br /><br />I suspect the move to the latest SDK changed some layout defaults which has cause some elements to take on a low contrast. In other cases like the confirmation dialog to mark all articles as read only the title is visible, with the actual warning text completely invisible.<br /><br />![Screenshot_20160814-091511.png](http://i.imgur.com/853lR8s.png)<br />

**Comment by abcminiuser** [comment]
The theme switcher also does nothing now.

**Comment by UksusoFF** [comment]
Confirmed. And on "All read" it's white on white.

**Comment by tgoz** [comment]
I've seen this too with both "dark" and "black" display themes. Switching to "light" or "white" does make the text visible, but I really prefer a darker screen.

**Comment by nilsbraden** [comment]
Noticed this too but after the release was out. Since it was not a big problem I left it that way. Next update will change this of course. Thanks for the report though!
