### ISSUE TITLE
connection closed by client while running TTRSS-reader for the first time

### ISSUE THREAD

**Issue by pmaziere** [nilsbraden/ttrss-reader-fork#322]
Hello,

I upgraded my ttrss server to the current HEAD, which also forced me to migrate from ttrss-reader 1.89 to 1.90.
Since I was using the F-droid version, I had to compile 1.90 myself and install it. And since the signatures are different, I had to uninstall 1.89 and all the data and cache have been erased.

Therefore the 1.90 install had to rebuild the application db and it seems that this is an issue when the ttrss server hosts a lot of data.

Here is what I can observe on the server part:
"POST /api/index.php HTTP/1.1" 200 100 "-"
"POST /api/index.php HTTP/1.1" 200 42738 "-"
"POST /api/index.php HTTP/1.1" 499 0 "-"

the last line is repeated until ttrss-reader decides it has enough and stop trying.
499 is a special code used by nginx to say that the client closed the connection before the server was able to send a response. And effectively, the postgresql server is using all the CPU power trying to answer the ttrss server queries, continuing even after I close ttrss-reader.
And I guess ttrss-reader repeats its query to the ttrss server for each line reporting this 499 HTTP error code.

Is there a timeout on the ttrss-reader side that can be modified so that the db initialization can be performed correctly ?

Thanks

**Comment by pmaziere** [comment]
after several attempts, it finally made it.
I did not change anything on my server or my phone, so I guess there is really an issue but I won't be able to reproduce it.
I'll let you decide if this issue should be closed or not.

**Comment by nilsbraden** [comment]
Default Timeout is 10 Seconds. If you compile yourself you can edit it here: https://github.com/nilsbraden/ttrss-reader-fork/blob/master/ttrssreader/src/main/java/org/ttrssreader/net/JSONConnector.java#L177

Do you know what request was sent exactly? I have never seen a server take 10 seconds to respond to any of the requests of the app since most are limited in the number of results that are provided by the API.
