### ISSUE TITLE
Random back button behavior

### ISSUE THREAD

**Issue by languitar** [nilsbraden/ttrss-reader-fork#335]
For me the back button behaves more or less randomly. Sometimes it goes back to the feed from an article, sometimes it goes back to the main view. Sometimes it goes back to a feed group from a feed, sometimes it directly goes back to the main view. I couldn't find any pattern that explains this behavior.

Currently running 1.91.1 (1991) on android 6

**Comment by nilsbraden** [comment]
Are you using the tablet layout? Not sure about that but I haven't experienced anything like this at all with the normal layout.

**Comment by languitar** [comment]
No, it's on a nexus 5.
