### ISSUE TITLE
Tumblr videos not playable

### ISSUE THREAD

**Issue by Lentzeris** [nilsbraden/ttrss-reader-fork#338]
GIFs from tumblr posts play automatically, but videos, which should have a play button in order to start on demand, are displayed as static pictures only with no ability to start playback.

**Comment by Lentzeris** [comment]
The problem is the same as with the browser version of TTRSS. It is **solved** by using the included plugin "af_zz_vidmute", but altering the script. In the part that says "setAttribute("muted", true)", if you change it to "setAttribute("controls", true)", the playback buttons become visible and the problem is solved.

I wonder if something similar can be done in the application...

**Comment by nilsbraden** [comment]
Does that mean we would have to add tumblr specific parsing and editing of feed content in the app? Shouldn't this be done server side or submitted to tumblr as a bug?
