### ISSUE TITLE
Next/Previous buttons doesn't work on Android 8

### ISSUE THREAD

**Issue by yorik** [nilsbraden/ttrss-reader-fork#347]

**Comment by yorik** [comment]
After upgrading to Android 8 TTRss reader stopped to go to next or previous article but instead it navigates to list of articles. But the article I want to go to becomes marked as read.

**Comment by rinhudio** [comment]
Same here on Android Oreo. But it is not just the volume buttons. Also 'swiping' to left/right to open the next/previous article is broken.
@nilsbraden Any chance that this get's fixed?

**Comment by fschlich** [comment]
Same issue also shows when using the on-screen navigation buttons. It is as if the next article is opened, but then the article window becomes invisible, showing the list behind it: while you can just choose any article from the list, pressing "back" will take you to ... just that same list of articles, NOT the list of feeds!

**Comment by MarcSchmitzer** [comment]
Seeing the same thing on my Nexus X5 since the upgrade to Oreo. I'd love to help get this fixed.

**Comment by gdhgdhgdh** [comment]
Same here on Nexus 5X after Oreo 8.0 upgrade. Some pics to help illustrate the problem ...

Initial state with all unread articles...

![screenshot_20171017-210231](https://user-images.githubusercontent.com/5349029/31686897-9db74c10-b37f-11e7-814b-6af66b62b809.png)

Tap on the first article...

![screenshot_20171017-210239](https://user-images.githubusercontent.com/5349029/31686911-ab34de66-b37f-11e7-9b8e-c18ab4024d9d.png)

Press Volume Down...

![screenshot_20171017-210249](https://user-images.githubusercontent.com/5349029/31686938-b91267ce-b37f-11e7-86bb-72725f6a1be0.png)

I expected to see the second article. Instead, the second article has been marked as read and I have been returned to the list of unread articles.

**Comment by maikbrueggemann** [comment]
Workaround: uncheck Preferences --> Display --> Enable Animations

**Comment by fschlich** [comment]
@maikbrueggemann YAY that works! Usability restored, at last :-)

**Comment by nilsbraden** [comment]
Can't test on Oreo since the A3 is still on Nougat, sry. But if disabling the animations helps its probably just a minor change to keep the right fragment on top because this sounds like the list (which is always kept in the background) gets to the front somehow.
