### ISSUE TITLE
SSL not working with imported self-signed CA

### ISSUE THREAD

**Issue by ingenium13** [nilsbraden/ttrss-reader-fork#354]
I seems bug #312 may not be fixed on Android 8.0 running 1.92.0 from the Play Store. I'm new to ttrss-reader, so I can't confirm previous builds worked.

I'm using a self-signed certificate with a CA that has been imported into Android. Loading the tt-rss url in Chrome works fine and validates. Other apps have no issues validating this certificate. I ensured that my server (using nginx) is using a chain of the CA and the cert. 

The only thing I can think of is perhaps the app isn't checking the SAN? My issued certificate has multiple DNS entries, and the URL I'm using is not the common name, but rather is listed as a SAN. 

I made the SSL settings as permissive as possible, disabling Google play services provider-installer, enabling accept all SSL certificates, and trusting all hosts. Shouldn't this make the app accept any certificate?

![screenshot_20170913-005230](https://user-images.githubusercontent.com/3280458/30360401-2c941e80-981f-11e7-8034-602e3f63d037.png)
![screenshot_20170913-005236](https://user-images.githubusercontent.com/3280458/30360404-2e823c18-981f-11e7-8cf9-9f0b98c11986.png)

**Comment by maikbrueggemann** [comment]
See #343
