### ISSUE TITLE
Error message "Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

### ISSUE THREAD

**Issue by busybit** [nilsbraden/ttrss-reader-fork#355]
I'm not able to establish a connection to my TT-RSS instance. (API is enabled). On startup I get the error:
"Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $ No Exception-Cause available".
Server is Tiny Tiny RSS v17.4 (153cb6d)
Client is Version 1.92.0 from Play store.
Android 7.1.2

Tiny Tiny RSS (TRIAL) from Andrew Dolgov works fine with the same server settings.

**Comment by nilsbraden** [comment]
The data returned from the server contains non JSON data and cannot be parsed correctly. Please follow the steps in the wiki to manually call the server API and see what it returns.

**Comment by feurich** [comment]
I had the same error and in my case an Apache RewriteRule caused the problem.
I used the Terminal and took a look at what
`curl -d '{"op":"login","user":"YourUsernameHere","password":"YourPwdHere"}' http://yourdomain.here/ttrss/api/ `
was putting out (Thanks to Nils for this hint!).
In my case the server returned plain HTML and no JSON at all. After fixing the rewrite, the app is working now. HTH someone.
