### ISSUE TITLE
Unwanted auto scroll

### ISSUE THREAD

**Issue by Mistress-Anna** [nilsbraden/ttrss-reader-fork#357]
Whenever I mark an article from the article list, the app uncontrollably decides to scroll randomly, so I lose the track of where I was. This is very unsettling, please disable that scroll.

**Comment by nilsbraden** [comment]
There is no scroll. If you want more help I need more information.

**Comment by Mistress-Anna** [comment]
So what causes the article list to go back on top when I mark an article?
