### ISSUE TITLE
Partial translation of settings in french

### ISSUE THREAD

**Issue by onthebeachbob** [nilsbraden/ttrss-reader-fork#359]
Everything works fine but the translation of settings in french is partial.
If you want, I can send you the missing translations in French.
Sincerely
Bob

**Comment by nilsbraden** [comment]
Please feel free to do this. Best would be to use the already submitted file from repository (https://github.com/nilsbraden/ttrss-reader-fork/blob/master/ttrssreader/src/main/res/values-fr/strings.xml) and just add the missing keys by comparing it with the english file so it can be easily merged.
