### ISSUE TITLE
mark as read marks articles that have never been seen

### ISSUE THREAD

**Issue by jr4** [nilsbraden/ttrss-reader-fork#365]
Mark as read appears to mark everything as read on the server, even things that have never been synced to the client.  This includes new articles that have come in, and sometimes much more because there's a 400 article limit on the sync.

**Comment by jr4** [comment]
Easiest solution might be to have "mark everything as read" use updateArticle with many IDs instead of catchupFeed.  That's essentially my workaround now, it's not too slow.

**Comment by nilsbraden** [comment]
Is it only 400? Thought I pitched that up to ~1000 a while back. Should do that anyway. But using updateArticles is the better solution here, thats right. Do you want to provide a pull request? I just updated to Oreo and got a cold so I want to spend some time on this project :)
