### ISSUE TITLE
Articles vanish without being read

### ISSUE THREAD

**Issue by thrawn-sh** [nilsbraden/ttrss-reader-fork#369]
Error only occurs since update to 1.9.3.0

I've sorted all my feeds into categories and only show unread feeds. Using the dark theme, "go back marks all items read" is not set

Steps to reporoduce:
1: choose a category
2: choose a feed
3: do not read any article in the feed, just leave feed (regardless of back button or "back arrow" in the action bar is used)
4: feed is not shown any more (even if I enable to show all feeds the feed is not shown anymore)
5: close the app and restart, to make the feed appear again (hitting refresh button in the app does not help)

I've wiped all data + configuration but problem remains

**Comment by nilsbraden** [comment]
Thanks for reporting. This should be fixed with Issue #370 in the next release.

**Comment by EwgB** [comment]
The fix is unfortunately only partial. The feed now no longer disappears (thank you for that!), but it goes to the top of the list and the name disappears. If I select a second feed and go back, the second one now has no name, and the first one had disappeared yet again.

**Comment by thrawn-sh** [comment]
Same for me, the name of the feed already disappears in the action bar, when I open the feed. I can see it for an instant and then it collapses and only the counter of unread news remains.
