### ISSUE TITLE
1.93.1 feedname not shown and empty in overview

### ISSUE THREAD

**Issue by frogshaving** [nilsbraden/ttrss-reader-fork#371]
Since the update to 1.93.1 on my android 6.0.1 the title of a feed is just empty within the feed's overview. It only states the number of unread articles. After having read all items and going back to the "new articles" overview, the title of the previous selected feed is empty there, too.

If requested, I can provide screenshots, but I have to wait for more articles to come in.

**Comment by mikroSlavek** [comment]
Hi. Same here (Android 5.0, 1.93.1, Tiny Tiny RSS v16.8). Video: https://www.youtube.com/watch?v=p2ZmlYPwHF0

**Comment by darix** [comment]
+1

**Comment by lotrdocker** [comment]
Hi, same problem for me.

**Comment by nilsbraden** [comment]
Should be fixed with the next version. Introduced with #368 where a wrong INSERT OR REPLACE was used to store the feed icon and the other not provided values where automatically set to NULL.

**Comment by darix** [comment]
any ETA for a new play store release?
