### ISSUE TITLE
Previous/next buttons don't work again

### ISSUE THREAD

**Issue by yorik** [nilsbraden/ttrss-reader-fork#374]
with new release previous/next button through back to articles list now with marking target article as read. Also clicking on it doesn't help. To fix you have to click back many times up to main screen. Enabling/disabling animation doesn't help this.

Also new icons waste to much space. It would be nice to disable them. Could you rollback until it will be fixed? Please!

Also new release waste more battery.

Android: 8.1.0

**Comment by reibuehl** [comment]
Same here. Since my Samsung S8 got the Android 8.0.0 update last Sunday, neither swiping left right nor using the volume up down buttons works to move between articles. Only going back to the article list, selecting the next article and then going back to the article list with back seems to work but is really cumbersome.

**Comment by virgoparna** [comment]
I'm having same problem in my Android Oreo (8.0.0) phone. But my tablet, that has Marshmallow, does not have this problem. 
Also, once the problem has occurred I need to got back from article list, because selecting other article marks it read without opening it. But when I go back from article and select another article, then it works.

**Comment by gdhgdhgdh** [comment]
Yeah, 1.93 is now unusable with current Android. I've had to uninstall and go back to 1.92. Please consider rolling back those changes!

**Comment by nilsbraden** [comment]
I didn't find a solution yet but I observed that it has something to do with the way fragments are overlayed with each other in the app. For the tablet layout I use the same fragments but display them side by side while they are stacked for the normal UI. Somehow switching to next/prev articles does not display the overlayed fragment but seems to catch some of the events while beeing invisible.

**Comment by virgoparna** [comment]
I don't have tablet layout enabled on my tablet (at 8" I found phone layout more comfortable).

**Comment by lim-on-air** [comment]
Hello, 
Same behavior here, on a Samsung S8 with android Oreo 8.0.0.
@nilsbraden Do you forsee a solution or is it complicated to solve ?

**Comment by rubinlinux** [comment]
Note8 att here, seeing this after oreo update as well

**Comment by virgoparna** [comment]
After last update it works. But I think I already had animations
disabled, so that alone is not issue.

	Also, was the github project deleted? I'm getting 404 at github web
browser.

-- 
Virgo Pärna
virgo.parna@mail.ee

**Comment by nilsbraden** [comment]
Suspended for no reason, no answer from support. Anyone fancy an alternative? Self-hosted is possible.

**Comment by rubinlinux** [comment]
Even with the update it was still broken, but turning off animations does seem to be a work-around.

The github project is not 404-ing for me. What happened exactly?

**Comment by reibuehl** [comment]
Turning off animations also helps for me with the latest version on my Samsung Galaxy S8 with Oreo (8.0.0).

**Comment by alkaphreak** [comment]
Hi, i got those bugs here from maybe more than a year now.

When i'm reading an article, and i swipe next, the app go back to the list, marking the next article read instead of going to next article like before.

My device is a SM-A520F with Android 8.0.0
