### ISSUE TITLE
Regression: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by protist** [nilsbraden/ttrss-reader-fork#376]
I've been using TTRSS-Reader for over a year now, and it has been working well (thank you!). I just updated to 1.93.1 via Google Play, and I can no longer connect. I get the following error.
```
SSLException in doRequest(): Exception-Message:
java.security.cert.CertPathValidatorException: Trust
anchor for certification path not found. Exception-
Cause: java.security.cert.CertificateException:
java.security.cert.CertPathValidatorException: Trust
anchor for certification path not found.
```
I've manually copied the message, so it may have typos. The screenshot is here:

[<img src="https://user-images.githubusercontent.com/646668/37699575-3e1bfe18-2d3c-11e8-8777-a2ad85a92cb8.png" width="100">](https://user-images.githubusercontent.com/646668/37699575-3e1bfe18-2d3c-11e8-8777-a2ad85a92cb8.png)

I tried installing the previous version 1.93.0 from the GitHub APK, but this also failed similarly. Finally, I reverted to 1.92.0, and it works perfectly again.

I see nothing obvious in my server's logs. I'm happy to troubleshoot further if necessary.

**Comment by nilsbraden** [comment]
Please try the build from here: https://github.com/nilsbraden/ttrss-reader-fork/releases/tag/v1.93.2
I changed the client certificate loading and moved some code around, hope this helps.

**Comment by protist** [comment]
Thank you! That works perfectly.

Thank you for the quick fix. I've also donated a small amount.

**Comment by michailf** [comment]
Did this break again?  I am using self-signed cert and everything connects except this app.  The error is the same as reported in this issue.
