### ISSUE TITLE
Wrong back button behavior after marking all read

### ISSUE THREAD

**Issue by ziffusion** [nilsbraden/ttrss-reader-fork#379]
When you have more than one feed in a category, back button misbehaves after marking "all read" in one of the feeds. Instead of going back one level up where other feeds in the category can be seen, it goes to the top level.

For example, if you have the following hierarchy:

Top level
-------- Category A
---------------- Feed 1
---------------- Feed 2

If you navigate to Feed 1 and mark all articles as read, and then press the back button, you will navigate back to the top level (instead of Category A).

**Comment by mnalis** [comment]
It is becauase you are too quick... if you wait a second or two, marking all as read will automatically perform "back". So if you *also* press back, there will be two "back" command sent.

You can disable that automatic "back" in Preferences/usage if you don't want it.

**Comment by ziffusion** [comment]
No, that's not the case.

The "automatic back" option (called "Go back after all items marked read")
is NOT checked. The behavior I see is that on marking all articles read, it
clears the unread count, and then displays ALL articles. Then if I hit the
back button, it goes one level up too many.
