### ISSUE TITLE
Fails to connect to self-signed server since Android Pie

### ISSUE THREAD

**Issue by airbete** [nilsbraden/ttrss-reader-fork#389]
Since I upgraded to Android Pie (Galaxy S8+), ttrss-reader fails to connect to my self-signed server over https. I get the message below

![image](https://user-images.githubusercontent.com/10148399/55567242-4192cb80-56cb-11e9-9211-f1f42da6cbe6.png)

I have tried several combinations in Preferences / SSL parameters with no success.

**Comment by nilsbraden** [comment]
Is this still an issue? No one else seems to have this problem.

**Comment by airbete** [comment]
It started to work again recently, but I have no idea why. :-/

I'll post again if the problem comes back. Thanks.
