### ISSUE TITLE
TTRSS-Reader 1.94.1 crashes at opening

### ISSUE THREAD

**Issue by Mer0me** [nilsbraden/ttrss-reader-fork#393]
I’ve juste updated TTRSS-Reader using F-Droid repository on two devices (Samsung S3 Phone and Samsung Galaxy Tab both running LineageOs / Android 7.1.2)
Both devices was running version 1.93.3 of TT-RSS Reader fine before update.
Both devices can’t launch TTRSS-Reader app after update to 1.94.1

The app simply crashes at opening. “TTRSS-Reader a cessé de fonctionné” (“TTRSS-Reader stops running”) even after rebooting the device.

Is there a workaround ? Am I alone with this bug ?

**Comment by nilsbraden** [comment]
F-Droid pulls the Tags and just builds them, same way I do but they are slower. So I push a new Tag, release it as beta release to the Play Store, find severe bugs on other platforms (my devices run Android 8.1 and 9, lots of problems come from older API levels), fix them, build a new release and in the same time I built and released 5 versions (1.94.0 to 1.94.4 which is kinda final) they only build and relese one. Maybe there are other options on their end to distinguish the release types? But you have to change the same release with some flag from beta to final at some point, dont know how this can be achieved.

**Comment by Mer0me** [comment]
Thank you.
