### ISSUE TITLE
The menu (three dots) is almost invisible when using dark theme

### ISSUE THREAD

**Issue by marteno** [nilsbraden/ttrss-reader-fork#394]
The three menu dots are almost invisible when using the dark theme as the dots are black as well in version 1.94.4. The refresh and mark-as-read are grey as in previous versions (clearly visible).
The actual menu when shown is light grey text on white background.
The extra explanations text in settings are also black on black background.

**Comment by nilsbraden** [comment]
Please provide me with the android version you are using since on my devices (Android 8.1 and Android 9) all the things you mention are different.

**Comment by marteno** [comment]
Sorry forgot to add it.
It is on Android 9 on oneplus 7 pro.
This has been as expected before (at least the three dots being clearly visible a bit uncertain about the text in the preference view)

**Comment by nilsbraden** [comment]
![Screenshot_20190913-140737_TTRSS-Reader~01](https://user-images.githubusercontent.com/369563/64861467-4e2f2e80-d630-11e9-97b2-b3d909d9fe9b.png)
![Screenshot_20190913-140729_TTRSS-Reader~01](https://user-images.githubusercontent.com/369563/64861470-525b4c00-d630-11e9-83e4-444e49d80d2c.png)
![Screenshot_20190913-140722_TTRSS-Reader~01](https://user-images.githubusercontent.com/369563/64861478-55eed300-d630-11e9-9d9a-5c4642ec3130.png)

**Comment by marteno** [comment]
This is how it looks for me
![Screenshot_20190913-134417](https://user-images.githubusercontent.com/25266197/64863407-0a8af380-d635-11e9-9145-220822a0f3ee.jpg)

![Screenshot_20190913-134427](https://user-images.githubusercontent.com/25266197/64863425-137bc500-d635-11e9-84a0-0efec50b4a39.jpg)

![Screenshot_20190913-134436](https://user-images.githubusercontent.com/25266197/64863444-2098b400-d635-11e9-92a6-07846c18b8f9.jpg)
