### ISSUE TITLE
Impossible to start app in 1.94.1

### ISSUE THREAD

**Issue by dominix** [nilsbraden/ttrss-reader-fork#395]
Impossible to start app in 1.94.1 and Impossible to downgrade to 1.93.3. So I am locked in non functional state.
This happen on galaxy tab sm-t585 android 8.1.0

**Comment by craigem** [comment]
I have experienced the same issue, via F-Droid on an Oppo Find7 and Samsung tablet.

**Comment by craigem** [comment]
v1.94.5 was just released. It's possible point releases 2-5 correct this issue. None of these versions are in F-Droid yet though.

**Comment by craigem** [comment]
The release notes:

https://github.com/nilsbraden/ttrss-reader-fork/releases

Make it clear that 1.94.1 should not be used.

I'll follow this up with F-Droid as they should not have built against this version.

**Comment by nilsbraden** [comment]
I explained the problem in #393 already and don't really know what to do currently. To upload an app to the play store beta program I feel I have to make sure the exact state is preserved so I tag and release it but leave the release as a draft. Or sould I just release it and add the Tag once it's a final release and goes to production?

**Comment by dominix** [comment]
I Was able To downgrade but only with a complete erase of all data and cache. I,ll try 1.94.5.

**Comment by dominix** [comment]
1.94.5 was not able to install. So I'll stick to 1.93.3
