### ISSUE TITLE
1.94.1 has lost important toolbar buttons

### ISSUE THREAD

**Issue by Mistress-Anna** [nilsbraden/ttrss-reader-fork#396]
Since 1.94.1, here's a sample of what ttrss-reader looks like on my phone:

![ttrss](https://user-images.githubusercontent.com/11899334/65078208-1c99c880-d98c-11e9-9b37-7fbe944e7d53.png)

Buttons like "mark all as read" have vanished. When viewing an article, buttons like "mark as favorite" have disappeared as well.

**Comment by nilsbraden** [comment]
Please provide full version information (1.94.5?) for the app and which Android version youre running.

**Comment by nilsbraden** [comment]
Only v1.94.5 is supported from now on, 1.94.1 was only a draft release.
