### ISSUE TITLE
Upper UI panel missing on Android 6.0 in latest version

### ISSUE THREAD

**Issue by virgoparna** [nilsbraden/ttrss-reader-fork#397]
In latest version UI panel is missing (the one with hamburger menu, refresh button and so on). 
Since menu is not available I cannot check exact version inside the app, but play store shows, that I have latest version and What's new has Version 1.94.5
Android 6.0, device is Lenovo TB3-850M (Tab3 8") screen is 800x1280 pixels and app was configured to not use Tablet mode.

**Comment by virgoparna** [comment]
Added screenshot

![Screenshot_20190918-194010](https://user-images.githubusercontent.com/5081457/65168801-f4729e00-da4d-11e9-8566-e3735b271809.png)

**Comment by virgoparna** [comment]
On my phone with Android 9 there are no issues.

**Comment by nilsbraden** [comment]
Huh thats odd. I got another complaint about this by Mail, same description so definitely a bug in the app but I haven't experienced it at all. Can you try swiping up and down, this should normally bring the menu into view?

**Comment by virgoparna** [comment]
Swiping does not bring it into view. Judging my phone configuration hide ActionBar was probably checked. But in screenshot there is not enough rows to scroll something. And when viewing feed with lot of posts swiping up/down does not show it either. Animations were probably also disabled, if that is somehow relevant. Unfortunately I cannot access preferences to check, if they somehow affect it.

**Comment by virgoparna** [comment]
I reset the configuration and tried from clear config: if I disable tablet layout, then that upper part disappears. Even if hide ActionBar is not checked.

**Comment by nilsbraden** [comment]
Thanks for debugging this issue. I reproduced it in the emulator with your device specs and found a case where the main layout was drawn above the toolbar. Should be fixed with the next version.
