### ISSUE TITLE
Can't read article - font too small

### ISSUE THREAD

**Issue by starox** [nilsbraden/ttrss-reader-fork#399]
v1.94.4 on android 9 (lineageos 16.0)

Fonts are too small to be read.

![Screenshot_20190920-194126_TTRSS-Reader](https://user-images.githubusercontent.com/1730254/65347488-675f4e80-dbdf-11e9-8c74-b4d1e579e2b0.png)

**Comment by nilsbraden** [comment]
1.94.4 is not a supported release.
