### ISSUE TITLE
Keine Einzelübersicht/-anzeige

### ISSUE THREAD

**Issue by Chritz85** [nilsbraden/ttrss-reader-fork#402]
Leider habe ich das Problem, dass ich nach antippen eines Feeds keine Einzelübersicht/-anzeige mehr bekomme. Es ändert sich nur die obere Leiste. 
Version 1.94.6 (Bilder im Anhang)
![Vorher](https://user-images.githubusercontent.com/56206936/66261053-3d08b600-e7c7-11e9-8414-609bd18b5ea0.png)
![Nachher](https://user-images.githubusercontent.com/56206936/66261055-41cd6a00-e7c7-11e9-852f-9dddfb99acee.png)

Cache geleert - keine Änderung
Neuinstallation - keine Änderung
Android 9 (Android One)
Aquaris X2

**Comment by nilsbraden** [comment]
Sounds like the issue described in #405, can you try to enable the tablet mode in preferences?

**Comment by Chritz85** [comment]
Mit der Aktivierung des Tablet Modus wird die geteilte Ansicht angezeigt. Allerdings löst das nicht das Problem, dass die Einzelanzeige alleine angezeigt wird. Aber man kann immerhin die Vorschau wieder anschauen.

**Comment by Chritz85** [comment]
Hi Nils,

Mit der Aktivierung des Tablet Modus wird die geteilte Ansicht angezeigt. Allerdings löst das nicht das Problem, dass die Einzelanzeige alleine angezeigt wird. Aber man kann immerhin die Vorschau wieder anschauen.

 


Viele Grüße
Chris 

Am 23. Oktober 2019 09:41:10 MESZ schrieb Nils Braden <notifications@github.com>:

**Comment by nilsbraden** [comment]
Ach so also auch im Tablet-Modus können Artikel dann nicht geöffnet werden oder wie?

**Comment by Chritz85** [comment]
Die kleine Vorschau auf den Artikel wird , wenn Tablet Modus aktiviert, dann unterhalb dargestellt. Früher wurde es in in einem "neuen Fenster" dargestellt. Also komplett geöffnet. Wenn ich den Link antippe wird er natürlich im Browser geöffnet.

Am 23. Oktober 2019 10:49:38 MESZ schrieb Nils Braden <notifications@github.com>:
