### ISSUE TITLE
Font too small, article unreadable in 1.94.6

### ISSUE THREAD

**Issue by dominix** [nilsbraden/ttrss-reader-fork#403]
With version 1.94.6 display of article render in a small font, so it becomes unreadable.  Is there any settings for the size of the default font ?

**Comment by virgoparna** [comment]
Preferences, Display, Text-Zoom in percent. After clearing app data mine was set to -1. setting it to 100% made it OK again.

**Comment by mnalis** [comment]
Thanks! This happened to me to fresh installation on 1.94.6 from F-droid. Changing it to `100` from default `-1` fixed it (after I closed the app, cleared it from recent apps list, and started again to force it to start anew - without that it just entered old broken version of app running in background)

**Comment by marlluslustosa** [comment]
This also happened to me. I resolved by changing from -1 to 100.
Version: 1.94.6 (f-droid)

**Comment by PrestonMcAfee** [comment]
With a fresh, first-time install, I also had the zoom = -1 problem, very off-putting for a first time user, though easily fixed.

**Comment by nilsbraden** [comment]
If it's so easy, why don't you stop complaining and asking other people to work for you and just provide a working and properly tested pull-request?
