### ISSUE TITLE
Version currently on PlayStore (1.94.6) simply crashes at start

### ISSUE THREAD

**Issue by liar666** [nilsbraden/ttrss-reader-fork#404]
Hi,

I've just updated my phones' version and now I'm just unable to open TTRSS-reader.

I've emptied the cache and removed all tha App data, still doesn't work.

FYI, I'm using an android 4.4 phone

Is there a way to get a log or something on Android, so that I can help you debug the problem?

**Comment by liar666** [comment]
After more testing, versions 1941 & 1944 from fdroid do not work either

Version 1.85.2 from apkpure works

**Comment by nilsbraden** [comment]
Please note: I have no idea what apkpure actually is and I'm not providing any builds to any other sites except the Google Play Store and the release-listing on Github.

If the app just crashes there should be output to logcat. Reading logs is described here: https://github.com/nilsbraden/ttrss-reader-fork/wiki/Troubleshooting

**Comment by arthurlutz** [comment]
Getting the same problem with the version from f-droid. Downgrading to 1.94.4 or 1.94.1 doesn't solve the problem. 

```
Model: Lenovo TAB 2 A10-70F
Android version : 4.4.4
```

@nilsbraden by the way thanks for an awesome app :heart:

**Comment by nilsbraden** [comment]
From F-Droid should be the current version. If you can, please follow the steps outlined here to acquire logs: https://github.com/nilsbraden/ttrss-reader-fork/wiki/Troubleshooting
Thank you!
