### ISSUE TITLE
Paste url button doesn't work

### ISSUE THREAD

**Issue by marteno** [nilsbraden/ttrss-reader-fork#406]
Opening subscribe screen and trying to press the "Paste url" text doesn't do anything (anymore).
Long pressing on the text line so the "regular" Android menu with paste option turns up works and the url can be pasted that way.

App version 1.94.6
Android version 10

**Comment by nilsbraden** [comment]
Should be fixed, please re-open if this is still an issue.

**Comment by marteno** [comment]
Weird. I still had this issue and thought I would try to record it. So to further be able to show I turned on "show touches" and "show pointer" in developer options (I think that is what they are called when English is the system language) and installed a screen recorder app....
But then it worked but only if the screen recorder app was recording.
Disabling the two options in developer settings didn't affect anything.
Also if the recorder app was not recording it didn't work and I tried two different recording apps

**Comment by marteno** [comment]
@nilsbraden I can't reopen this but see my comment above and reopen it or let me know if I should open a new one instead (or any other action).

**Comment by nilsbraden** [comment]
It's an android 10 issue. I had the status of the button attached to the availability of a Primary-Clip but on android 10 you can only access the clipboard if you have focus. This was not the case in onResume and since there is no lifecycle method after onResume I can't check it. So now the button is always enabled but does nothing if there is no clip available.

**Comment by marteno** [comment]
Ah of course it is fixed "now" as the code is merged but I guess it has not been any release with this fix... Didn't think it thru, sorry for the noise (if you see this)

**Comment by nilsbraden** [comment]
No worries and thanks for checking it quickly anyway! :)

I changed some more internals (translations and layout fixes mostly) that are also already committed but don't really justify a new release so I attached a release-build here: https://github.com/nilsbraden/ttrss-reader-fork/releases/tag/1.94.x_debug

**Comment by marteno** [comment]
Downloaded and tested it, it works now.
Thanks.
