### ISSUE TITLE
Make Feed-Icons larger?

### ISSUE THREAD

**Issue by PrestonMcAfee** [nilsbraden/ttrss-reader-fork#414]
![Screenshot_20200512-114427](https://user-images.githubusercontent.com/41998813/81733017-353c7e80-9446-11ea-985a-aed903f2fe35.jpg)

It would be much more useful to me if the large RSS page icon on the left were replaced with the feed icon, which currently is tiny.

**Comment by nilsbraden** [comment]
In my experience the feed icons normally don't have the necessary quality to view them at a larger scale, thats why I put them in small containers. If there is a non-ugly way of changing the UI to have them displayed bigger I'm going to make use of it but someone needs to find and build it. Pull-requests are welcome.
