### ISSUE TITLE
http authentication not sent

### ISSUE THREAD

**Issue by pmaziere** [nilsbraden/ttrss-reader-fork#415]
Hello,

I've just upgraded to 1.94.8 from 1.93.3.
It seems that the http authentication is failing as my server returns a 401 error and its log displays a dash instead of the http auth username, as if it did not receive any 'Authentication' field.

From what I see in the git log, commit cdf43dae8c032031d957931696fc0ee4278f10cd seems to be the last one modifying http auth. 

Thanks to verify that the behavior I observe is actually a bug that should be fixed, or if I have to verify something else on my side.

**Comment by pmaziere** [comment]
my bad, 18h later, without touching anything, it now works as expected

**Comment by nilsbraden** [comment]
Thanks for reporting. I guess it was a caching issue since the http-auth data was stored in an object that was not refreshed properly when the data changed in the preferences.
