### ISSUE TITLE
Number of unread articles disappeared

### ISSUE THREAD

**Issue by marteno** [nilsbraden/ttrss-reader-fork#417]
![Screenshot_20200618-092911__01](https://user-images.githubusercontent.com/25266197/84991728-35b3ed80-b147-11ea-8556-fa7a7a6a0ca0.jpg)
In version 1.95.0 the number of unread articles disappeared.

The whole top seems a bit "off" compared to earlier versions like it doesn't fit or something

**Comment by nilsbraden** [comment]
Oh I overlooked that number but I'm actually unsure when I saw it the last time. What android version are you using?

**Comment by marteno** [comment]
Android 10.
I am pretty sure I saw it before the update as I am using it to determine if I should (force) close the app due to issue 408.

**Comment by nilsbraden** [comment]
Should work again with the next update. I'll try to find a solution for #408 and then push it to the store.

**Comment by marteno** [comment]
Thanks
