### ISSUE TITLE
Unable to connect to TLSv1.3 Server

### ISSUE THREAD

**Issue by poldi1405** [nilsbraden/ttrss-reader-fork#421]
When attempting to connect to my instance at https://ttrss.moritz.sh the attached error is thrown. 
![Screenshot_20200813-215124](https://user-images.githubusercontent.com/33086936/90180998-0cfb4d80-ddb0-11ea-8d7a-5d927a447622.png)

It's Version 1.95.8.

The used phone is a razer phone 2. Android Pie, Security updates from 5th March 2020, Kernel Version 4.9.112

**Comment by nilsbraden** [comment]
Please have a look at #416 and this comment specifically: https://github.com/nilsbraden/ttrss-reader-fork/issues/416#issuecomment-668765282

**Comment by poldi1405** [comment]
Yes, I already tried multiple times with and without the checkbox enabled.

It's always the same message.

**Comment by nilsbraden** [comment]
You need to explicitly kill the app in between or restart the phone because once loaded, the play libraries can't be unloaded for the app.
