### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [nilsbraden/ttrss-reader-fork#438]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
> The task or issue was closed as completed by **mondlicht-und-sterne** on **February 11, 2021**.

@nilsbraden, the screenshots have disappeared again:

![Image](https://github.com/user-attachments/assets/9e1f5464-81c2-4fb9-aaab-a6e104ff26c6)
