### ISSUE TITLE
Login errors

### ISSUE THREAD

**Issue by strowi** [nilsbraden/ttrss-reader-fork#439]
Hi,

thx for the ttrss-app ;)

I'm having trouble syncing the feeds with the app, error message says login is incorrect.

Debugging i found some changes in ttrss-repo and could pinpoint problems started with the following commit:  
https://git.tt-rss.org/fox/tt-rss/commit/59c14e9c0001bc7a01763ecc7d3042dcde978a1a

```
~> curl -d '{"op": "login", "user": "xyz", "password": "123"}' https://rss.abc.net/api/ -vL
```
still works with current version though.

regards,
Roman

**Comment by Obererpel** [comment]
Yep, ran into this problem, too. The app converts the password to base64, but ttrss does not accept this anymore.

This is a game breaker, so someone should fix this asap. Is Nils still actively developing this app or should I learn how to compile android apps now :)

**Comment by TwizzyDizzy** [comment]
Indeed. This is the exact commit breaking app-compatability: https://git.tt-rss.org/fox/tt-rss/commit/59c14e9c0001bc7a01763ecc7d3042dcde978a1a

Cheers
Thomas

**Comment by webworxshop** [comment]
I've just submitted a trivial PR fixing this issue, which works well for me.

For those that use this app on a daily basis and can't wait for this to be merged/released, I've uploaded a patched APK at: https://cloud.webworxshop.com/s/qsS57FRLwLkJAZX (usual caveats about installing random APKs from the Internet apply).

**Comment by nilsbraden** [comment]
Thanks for providing the fix! I didn't update the server recently and didn't notice this yet.
