### ISSUE TITLE
Going to next article requires screen rotation to show content

### ISSUE THREAD

**Issue by virgoparna** [nilsbraden/ttrss-reader-fork#470]
Since version 1.97.2
When entering to feed, that contains multiple unread articles first article shows up fine. But moving next shows blank space at content part. Only after rotating tablet 90 degrees does the content show up. I have navigation buttons set to be always visible and those also do not appear before rotation. 
Device is Lenovo TB3-850M
Android 6.0
Tablet-layout is enabled.
#466 seems to describe same issue but was then marked as fixed by the original reporter.

**Comment by nilsbraden** [comment]
Should be fixed with #473
